### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by wojtaseu** [michaelarnauts/comfoconnect#33]
I am getting the below error when I am trying to connect to my Zehnder. 2 weeks back I was able to connect but now I am not not able.

Traceback (most recent call last):
  File "C:\Users\LN434UJ\Envs\reku\example\example.py", line 193, in <module>
    main()
  File "C:\Users\LN434UJ\Envs\reku\example\example.py", line 56, in main
    bridge = bridge_discovery()
  File "C:\Users\LN434UJ\Envs\reku\example\example.py", line 29, in bridge_discovery
    bridges = Bridge.discover('192.168.0.115')
  File "C:\Users\LN434UJ\AppData\Local\Programs\Python\Python39\lib\site-packages\pycomfoconnect\bridge.py", line 38, in discover
    data, source = udpsocket.recvfrom(100)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by michaelarnauts** [comment]
I'm not sure why this happens, but an older firmware only supported one active session. It's possible that the session was closed by another connection.

In a later firmware version of the Comfoconnect LAN C, the maximum of active connections is increased to 5, so I suggest to update to that firmware first.
