### ISSUE TITLE
Exception in _handle_update when dispatching comfoconnect_update

### ISSUE THREAD

**Issue by roofburner** [michaelarnauts/comfoconnect#62]
Hi,

Zehnder ComfoAirQ, installed via HACS

Version: a308546

I don't know if I'm the only one seeing this error in the home-assistant log.

```ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
Traceback (most recent call last):
  File "/config/custom_components/comfoconnect/sensor.py", line 410, in _handle_update
    self._attr_native_value = self.entity_description.mapping(value)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comfoconnect/sensor.py", line 333, in <lambda>
    mapping=lambda x: "" if x is None else x[0],
                                           ~^^^
IndexError: list index out of range
```

It seems everything is working fine, just putting the question here...

Indication of reoccurence:

```
2023-10-11 19:36:35.662 ERROR (SyncWorker_3) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-11 20:10:05.695 ERROR (SyncWorker_0) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 02:32:07.677 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:18:55.552 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:24:04.595 ERROR (SyncWorker_4) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:45:30.542 ERROR (SyncWorker_5) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:51:23.510 ERROR (SyncWorker_9) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:54:37.508 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 03:54:38.527 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 04:06:09.470 ERROR (SyncWorker_8) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 04:52:23.349 ERROR (SyncWorker_7) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 04:57:17.345 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 04:57:18.365 ERROR (SyncWorker_9) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:00:49.337 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:04:47.327 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:04:48.345 ERROR (SyncWorker_9) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:20:43.288 ERROR (SyncWorker_10) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:27:47.268 ERROR (SyncWorker_11) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:34:47.248 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:41:55.188 ERROR (SyncWorker_11) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:44:25.229 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:48:48.229 ERROR (SyncWorker_10) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 05:55:30.223 ERROR (SyncWorker_0) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:02:51.170 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:05:29.175 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:06:23.160 ERROR (SyncWorker_2) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:39:24.115 ERROR (SyncWorker_8) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:55:09.055 ERROR (SyncWorker_3) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 06:55:10.080 ERROR (SyncWorker_0) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 07:06:47.007 ERROR (SyncWorker_5) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 07:34:53.967 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:26:42.516 ERROR (SyncWorker_11) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:30:14.512 ERROR (SyncWorker_5) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:34:25.528 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:34:26.538 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:35:06.505 ERROR (SyncWorker_9) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:35:07.516 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:38:16.487 ERROR (SyncWorker_3) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:42:28.472 ERROR (SyncWorker_0) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 10:54:27.460 ERROR (SyncWorker_4) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 11:03:48.384 ERROR (SyncWorker_8) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 11:42:22.321 ERROR (SyncWorker_11) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 11:49:48.270 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 11:56:57.318 ERROR (SyncWorker_10) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 12:07:14.266 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 12:07:15.283 ERROR (SyncWorker_5) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 13:16:07.124 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 13:21:01.092 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
2023-10-12 13:21:07.108 ERROR (SyncWorker_1) [homeassistant.util.logging] Exception in _handle_update when dispatching 'comfoconnect_update_00000000001210138001144fd71e1811_230': ([],)
```

**Comment by michaelarnauts** [comment]
I would suggest to use the new version available on HACS: https://github.com/michaelarnauts/home-assistant-comfoconnect
